Feature cpu temp
DanBeluchi/sdp_project pull request #4
Opened 2022-12-13 18:53 UTC by TaOcM89

inplement cpu temp

2022-12-14 14:17 UTC, DanBeluchi requested changes
please add the module gpiozero to the requirement file (base.txt)

2022-12-15 12:58 UTC, TaOcM89 commented
gpiozero was added to base.txt

2023-01-07 09:26 UTC, silvio-io approved these changes

2023-01-07 09:29 UTC, DanBeluchi approved these changes

2023-01-07 09:29 UTC, merged